const qtdeQuartos = [
  {
    n_quarto: 0,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 1,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 2,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 3,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 4,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 5,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 6,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 7,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 8,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 9,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 10,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
  {
    n_quarto: 11,
    data_entrada: '',
    data_saida: '',
    disponivel: true,
    cliente: '',
  },
];
export default qtdeQuartos;
